### ISSUE TITLE
inprocess unavailable

### ISSUE THREAD

**Issue by twdp** [rpcxio/rpcx-examples#11]
目录：github.com/rpcx-ecosystem/rpcx-examples3/registry/inprocess
执行：go run serverandclient.go
结果：2019/02/12 10:58:54 failed to call: service Arith not found

**Comment by twdp** [comment]
额，用错了分支，3.0 inprocess是正常的，4.0和master都不行。

**Comment by smallnest** [comment]
fixed. support 4.0和master。 建议你使用master, 3.0不再维护了
