### ISSUE TITLE
run gracefule_restart example failed

### ISSUE THREAD

**Issue by supermario1990** [rpcxio/rpcx-examples#19]
https://github.com/rpcxio/rpcx-examples/blob/e96cba32d5e8cf1d420c05c01abde5edcd3e1930/graceful_restart/server.go#L33
I checked rpcx souce code, there is not a listener type called "reuseport". so when i run example it panic err "can not make listener for reuseport".

**Comment by smallnest** [comment]
windows does not support reuseport. It only can run linux > 2.8 or mac
