### ISSUE TITLE
MsgPack server example

### ISSUE THREAD

**Issue by 13o6** [rpcxio/rpcx-examples#2]
Hi @smallnest,
I was going through the examples as well as the rpcx source code repo but couldn't find an example of MsgPack codec used in a server. 
Furthermore, I tried finding one in https://github.com/vmihailenco/msgpack and couldn't find one. 
I'd appreciate if you can provide a snippet of how a server using `msgpack` would look like.

Thanks!

**Comment by smallnest** [comment]
msgpack is the default code. you can run any example in rpcx-examples
