### ISSUE TITLE
etcdv3报错

### ISSUE THREAD

**Issue by 582727501** [rpcxio/rpcx-examples#20]
https://github.com/rpcxio/rpcx-examples/tree/master/registry/etcdv3

操作这个example报错。
etcd：
etcd Version: 3.4.9
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.14.3
Go OS/Arch: darwin/amd64

报错1:
etcd的报错
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/07/14 15:41:25 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"

client端端报错：
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch
2020/07/14 15:41:25 etcdv3_discovery.go:244: WARN : chan is closed and will rewatch

server报错3:
server连上后，重新关闭，再开启
2020/07/14 15:42:56 etcdv3.go:66: ERROR: cannot create etcd path /rpcx_test: rpc error: code = Canceled desc = grpc: the client connection is closing
2020/07/14 15:42:56 rpc error: code = Canceled desc = grpc: the client connection is closing
exit status 1

怎么弄，大佬

**Comment by smallnest** [comment]
github.com/smallnest/libkv-etcdv3-store 使用最新的库
