### ISSUE TITLE
go get rpcx error

### ISSUE THREAD

**Issue by dezhenglu** [rpcxio/rpcx-examples#23]
Follow the manual （https://doc.rpcx.io/part1/quickstart.html）
go -get command
The following error will appear, how to solve it

smallnest/rpcx/codec/codec.go:129:15: not enough arguments in call to d.Read
	have (thrift.TStruct, []byte)
	want (context.Context, thrift.TStruct, []byte)

**Comment by smallnest** [comment]
使用go module方式，或者按照go.mod中的依赖库的thrift版本
