### ISSUE TITLE
gracefule_restart kill 重启后报 gateway http Server closed

### ISSUE THREAD

**Issue by gotid** [rpcxio/rpcx-examples#24]
**kill -HUP 重启后，报 gateway http Server closed**
---

#### 执行 kill
➜  did git:(master) ✗ kill -HUP 2044  

#### 服务端输出
2020/09/29 18:10:06 server.go:175: INFO : server pid:2044
2020/09/29 18:10:31 server.go:764: INFO : restart a new rpcx server: 2063
2020/09/29 18:10:31 server.go:175: INFO : server pid:2063
2020/09/29 18:10:34 server.go:706: INFO : shutdown begin
2020/09/29 18:10:34 server.go:798: INFO : need handle in-processing msg size:0
2020/09/29 18:10:34 gateway.go:78: ERROR: error in gateway Serve: *errors.errorString http: Server closed
panic: http: Server closed

goroutine 19 [running]:
main.main.func1(0xc0002862a0)
        /Users/zs/git/projects/did/graceful_restart/server.go:35 +0x85
created by main.main
        /Users/zs/git/projects/did/graceful_restart/server.go:32 +0x107

Process finished with exit code 2

---
#### 运行环境
go1.15.2 darwin/amd64

**Comment by smallnest** [comment]
fixed
