### ISSUE TITLE
demo中下载的例子不好用

### ISSUE THREAD

**Issue by yongliu1992** [rpcxio/rpcx-examples#25]
https://github.com/rpcxio/rpcx-examples/tree/master/file_download

在服务器端启动server

在本地电脑上启动client

会报错，无法成功下载文件,如果是在同一个电脑上执行 是没问题的，但是跨机器就不行了。

**Comment by smallnest** [comment]
提问题要把配置，错误信息都贴上，否则别人分析呢

**Comment by yongliu1992** [comment]
> 提问题要把配置，错误信息都贴上，否则别人分析呢

我在远程linux 服务器端开启了 8800 8801 2个端口，阿里云及防火墙我都打开了
./hk_rpc_tmp_server --addr=:8800 --transfer-addr=:8801
服务端 等客户端连接后 会出现这样的日志
2021/02/01 08:05:14 server.go:182: INFO : server pid:1400650
2021/02/01 08:06:14 server.go:380: INFO : client has closed this connection: 1.203.166.4:17849
  ^C

客户端使用的代码 
https://github.com/rpcxio/rpcx-examples/tree/master/file_download/client
https://github.com/rpcxio/rpcx-examples/blob/master/file_download/oneclient/oneclient.go
在本机 苹果电脑使用源码运行 ，客户端会报这样的错误
➜  rpcx_learn go run cli.go --addr=39.98.124.196:8800
panic: dial tcp :8801: connect: connection refused

goroutine 1 [running]:
main.main()
        /Users/kok/go/src/rpcx_learn/cli.go:32 +0x379
exit status 2

**Comment by smallnest** [comment]
服务端文件下载支持配置 AdvertiseIP

**Comment by smallnest** [comment]
服务端设置  AdvertiseAddr ,这是客户端要访问的地址

```
	p := server.NewFileTransfer(*fileTransferAddr, saveFilehandler, nil, 1000)
	p.AdvertiseAddr = "39.98.124.196:8801"
	s.EnableFileTransfer(share.SendFileServiceName, p)
```
