### ISSUE TITLE
Use consul as registry can't show Services Name

### ISSUE THREAD

**Issue by redwolf2019** [rpcxio/rpcx-examples#28]
I was try to run this example:https://github.com/rpcxio/rpcx-examples/tree/master/registry/consul
the `server` "register succed":
- `client` can call `server` rpc method.
- `consul` ui `Key / Value` area have `server` properties.
- `consul` ui `Services ` area did't show `server` name.
![image](https://user-images.githubusercontent.com/54215370/116505452-7cd54800-a8ed-11eb-9087-02baa13248ed.png)
![image](https://user-images.githubusercontent.com/54215370/116505462-8494ec80-a8ed-11eb-9092-8c0024ae1b0b.png)

I expect `consul` ui `Services ` area show register rpcx services name, what should i do? :)

**Comment by smallnest** [comment]
rpcx use consul k/v, not consul service
