### ISSUE TITLE
register demo error

### ISSUE THREAD

**Issue by wangwanttt** [rpcxio/rpcx-examples#3]
func addRegistryPlugin(s *server.Server) {

	r := &serverplugin.ConsulRegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		ConsulServers:  []string{*consulAddr},
		BasePath:       *basePath,
		Metrics:        metrics.NewRegistry(),
		UpdateInterval: time.Minute,
	}
error :
undefined: serverplugin.ConsulRegisterPlugin

**Comment by smallnest** [comment]
see README.md in rpcx
