### ISSUE TITLE
404 error for go get 

### ISSUE THREAD

**Issue by xiantong34** [rpcxio/rpcx-examples#36]
go get github.com/rpcxio/rpcx-examples
go: downloading github.com/rpcxio/rpcx-examples v1.1.6
go: github.com/rpcxio/rpcx-examples@v1.1.6: verifying module: github.com/rpcxio/rpcx-examples@v1.1.6: checking tree#15389948 against tree#15439110: reading https://goproxy.io/sumdb/sum.golang.org/tile/8/1/234: 404 Not Found
        server response: not found

**Comment by smallnest** [comment]
goproxy.io的问题，你换goproxy.cn试试。

这个版本存在的，并且我测试可以拉取。

<img width="486" alt="image" src="https://user-images.githubusercontent.com/865763/217131670-506f7218-8e06-489f-9d84-65b1416e9428.png">

**Comment by xiantong34** [comment]
very good ths.
