### ISSUE TITLE
registry/consul error

### ISSUE THREAD

**Issue by worldyuan** [rpcxio/rpcx-examples#4]
The demo can run.but key is localhost:8500/v1/kv/rpcx_test(server.go) not localhost:8500/v1/kv/rpcx_test/Arith(client.go)

**Comment by smallnest** [comment]
then what is your issue?

**Comment by worldyuan** [comment]
sorry, I write it error
r := serverplugin.ConsulRegisterPlugin{}
followed is right
it r := &serverplugin.ConsulRegisterPlugin{}
