### ISSUE TITLE
最新pkg中缺失方法WithBlockCrypt()

### ISSUE THREAD

**Issue by mkshift** [rpcxio/rpcx-examples#64]
在kcp 所在的demo中，有个WithBlockCrypt()方法，但在 [v1.8.24](https://pkg.go.dev/github.com/smallnest/rpcx@v1.8.24/server#Server) 中没有找到该方法并且最新代码中一直显示该方法undefined 未定义的引入。

是不是可以认为v1.8.24摒弃了rpcx 以kcp协议承载方式rpc server。

**Comment by smallnest** [comment]
方法存在。 请注意使用-tags kcp

https://github.com/smallnest/rpcx/blob/master/server/kcp.go#L25
