### ISSUE TITLE
KCP Example server WithBlockCrypt unresolved reference

### ISSUE THREAD

**Issue by richp10** [rpcxio/rpcx-examples#7]
Exact code as shown in the KCP example - 

s := server.NewServer(server.WithBlockCrypt(bc))

This line cannot be compiled as the .WithBlockCrypt is an unresolved reference (kcp is visble)

**Comment by smallnest** [comment]
Did you use latest rpcx? Did you add kcp inbuildtags?
`WithBlockCrypt `  exists in  https://github.com/smallnest/rpcx/blob/master/server/kcp.go

**Comment by richp10** [comment]
Thanks - that fixed it..

**Comment by richp10** [comment]
Runs.. however - it now shows INFO "network is not tcp/tcp4/tcp6 so can not start gateway" - looking at the code, using value for s.Serve of kcp will always show this message so maybe does not matter. 

The client successfully connects to the server and gets the response - but with packet inspection I see *lots* of 'unknown destination' packet errors, which keep coming in even after the client exits. Any thoughts?

**Comment by smallnest** [comment]
You can ignore the INFO log . It only works for tcp transport.

For the second case, I think it should be the kcp-go issue.
