### ISSUE TITLE
如何使用rpcx传送文件？

### ISSUE THREAD

**Issue by kidnet** [rpcxio/rpcx-examples#9]
rpcx是否可以传送文件？是否有stream方式？需要自己实现么？

**Comment by smallnest** [comment]
rpc目标时服务调用，不是用来传输数据，所以不建议使用rpcx传递文件。

**Comment by kidnet** [comment]
了解，一般的rpc框架都会有传输数据的功能(之前用过Thrift和gRPC都有对应的功能)。
